###
GET localhost:5000/api/todos

###
POST localhost:5000/api/todos
content-type: application/json

{
  "body": "parfums"
}

###
POST localhost:5000/api/todos
content-type: application/json

{
  "body": "de"
}

###
POST localhost:5000/api/todos
content-type: application/json

{
  "body": "marly"
}

###
PATCH localhost:5000/api/todos/66f540abcdcd5c7fdc1301f0

###
DELETE localhost:5000/api/todos/66f540afcdcd5c7fdc1301f1

